

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_150 = Integer(150)
P = _sage_const_2 
N = _sage_const_150 

def load_matrix(fname):
    data = open(fname, 'r').read().strip()
    rows = [list(map(int, row)) for row in data.splitlines()]
    return Matrix(GF(P), rows)
    

B_pub=load_matrix('bob.pub')
print(B_pub.parent())

G=load_matrix('generator.txt')

print(G)

#eigenval=list(G.eigenvalues())
#print(B_pub.eigenvalues())

print(G.multiplicative_order())
#find x such that G^x = I

print(G.parent())



