

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_8 = Integer(8); _sage_const_50 = Integer(50); _sage_const_31337 = Integer(31337); _sage_const_34 = Integer(34)
import random

def long_to_bytes(s):
	return s.to_bytes(_sage_const_1 , 'big')

def bytes_to_binary(s):
    bin_str = ''.join(format(b, '08b') for b in s)
    bits = [int(c) for c in bin_str]
    return bits

def generate_mat():
    while True:
        msg = bytes_to_binary(FLAG)
        msg += [random.randint(_sage_const_0 , _sage_const_1 ) for _ in range(N*N - len(msg))]
        #print(len(msg))
        print(msg)

        rows = [msg[i::N] for i in range(N)]
        print(rows)
        mat = Matrix(GF(_sage_const_2 ), rows)
        print(mat)
        return mat
        break

        if mat.determinant() != _sage_const_0  and mat.multiplicative_order() > _sage_const_10 **_sage_const_12 :
            return mat
            
def load_matrix(fname):
    data = open(fname, 'r').read().strip()
    rows = [list(map(int, row)) for row in data.splitlines()]
    return Matrix(GF(P), rows)

def print_mat(A):
	print('\n'.join(''.join(str(i) for i in rows) for rows in A))

def egcd(a, b):
    if a == _sage_const_0 :
        return (b, _sage_const_0 , _sage_const_1 )
    else:
        g, y, x = egcd(b % a, a)
        return (g, x - (b // a) * y, y)
def mod_inv(a,p):
	#a*u+b*v = 1 if (gcd(a,b)=1)
	#a*u = 1 mod b
	# 
	gcd, u, v= egcd(a,p)
	print(gcd, u ,v)
	return u%p
	
def bin_to_bytes(s):
    all_bytes = [s[i:i+_sage_const_8 ] for i in range(_sage_const_0 , len(s), _sage_const_8 )]
    return b''.join(long_to_bytes(int(byte, _sage_const_2 )) for byte in all_bytes)

P = _sage_const_2 
N = _sage_const_50 
E = _sage_const_31337 

A=load_matrix("flag.enc")
print(A)

g=multiplicative_order(A)
D=mod_inv(E,g)
print(D)
mat=A**D


cols = mat.columns()[:(_sage_const_34 *_sage_const_8 //_sage_const_50 )+_sage_const_1 ]

bin_flag = ''.join([str(bit) for col in cols for bit in col])

print(bin_to_bytes(bin_flag))





